// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txvhdpkcnkfcekwgmyaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4dmhkcGtjbmtmY2Vrd2dteWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODQ1OTUsImV4cCI6MjA3MzA2MDU5NX0.8J_tgye4bdUqUXwtfUsKjEif8OxzzWScAWzA8MhAlfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});